replicaCount: 1

image:
  repository: containers.renci.org/translator-dev/pred-mapping
  tag: v0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6380

env:
  HOME: /tmp/pred_mapping
  JINA_HOME: /tmp/pred_mapping/.jina
  LLM_API_URL: https://healpaca.apps.renci.org/api/generate
  CHAT_MODEL: HEALpaca-2.0
  EMBEDDING_URL: https://healpaca.apps.renci.org/api/embeddings
  EMBEDDING_MODEL: nomic-embed-text

volume:
  name: cache-volume
  mountPath: /tmp/.cache
  size: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: pred-mapping.apps.renci.org  
      paths:
       - path: /
         pathType: ImplementationSpecific
  tls:
   - secretName: pred-mapping.apps.renci.org-tls
     hosts:
       - pred-mapping.apps.renci.org

resources:
  requests:
    memory: 10Gi
    cpu: "500m"
  limits:
    memory: 10Gi
    cpu: "1"

