apiVersion: v1
kind: Service
metadata:
  name: {{ include "pred-mapping.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6380
  selector:
    app: {{ include "pred-mapping.fullname" . }}

