# Default values for nemo-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renci/nemo-sapbert
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "22.01"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

train:
  resources:
    limits:
      cpu: 2
      memory: 380Gi
      ephemeral-storage: 10Gi
      nvidia.com/mig-3g.20gb: 1
  command: "/data/code/train/pretrain.sh"
  storage:
    dataStorageSize: 20Gi
    experimentsStorageSize: 20Gi
    scratchStorageSize: 100Gi
    codeDirStorageSize: 1Gi

