# Default values for nemo-web-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/renci-ner/nemo-serve
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.3.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: med-nemo.apps.renci.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: med-nemo.apps.renci.org-tls
     hosts:
       - med-nemo.apps.renci.org


storage:
  size: 2Gi

modelConfig:
  downloadModels: true
  models:
    token_classification:
      repoUrl: "https://stars.renci.org/var/ner/models/"
      fileName: "medmentions-v0.2.nemo"
      class: "TokenClassificationWrapper"

resources:

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 12
    memory: 10Gi
    nvidia.com/mig-1g.5gb: 1
    ephemeral-storage: 10Gi

  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

annotate:
  enabled: false
  dataUrl: https://stars.renci.org/var/ner/pubmed/split_11.txt
  modelName: token_classification
  storage:
    modelsStorageSize: 10Gi
    dataStorageSize: 10Gi
    devShm: 10Gi