#
# This deployment can be used for running jupyter enabled mode for
# Actual running please use a job instead
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-helm.fullname" . }}
  labels:
    {{- include "nemo-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jupyter.service.type }}
  ports:
    - port: {{ .Values.jupyter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nemo-helm.selectorLabels" . | nindent 4 }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nemo-helm.fullname" . }}
  labels:
    {{- include "nemo-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nemo-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.jupyter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nemo-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.jupyter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.jupyter.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.jupyter.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 12 }}
          command:
            - jupyter
          args:
            - notebook
            - "--ip=*"
            - --NotebookApp.password={{ .Values.jupyter.password }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8888
          volumeMounts:
            - name: code-dir
              mountPath: "/code/"
            - mountPath: /data
              name: "data-dir"
            - mountPath: /exp
              name: "experiment-dir"
      volumes:
        - name: code-dir
          persistentVolumeClaim:
            claimName: "{{ include "nemo-helm.fullname" . }}-code-pvc"
        - name: data-dir
          persistentVolumeClaim:
            claimName: "{{ include "nemo-helm.fullname" . }}-trainer-data-pvc"
        - name: experiment-dir
          persistentVolumeClaim:
            claimName: "{{ include "nemo-helm.fullname" . }}-trainer-experiments-pvc"