{{- $fullName := include "nemo-helm.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-trainer-data-pvc"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.trainer.storage.dataStorageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-trainer-experiments-pvc"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.trainer.storage.experimentsStorageSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-code-pvc"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.trainer.storage.codeDirStorageSize }}