{{- $fullName := include "nemo-sapbert-helm.fullname" . -}}
{{- $image := .Values.image.repository }}
{{- $imageTag := .Values.image.tag }}
{{- $pullPolicy := .Values.image.pullPolicy }}
{{- $resources := .Values.inference.resources }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ $fullName }}-sapbert-inference-pod"
spec:
  containers:
    - name: inference-container
      image: "{{ $image }}:{{ $imageTag }}"
      imagePullPolicy: "{{ $pullPolicy }}"
      env:
        - name: PYTHONPATH
          value: "/data/code"
      command: ["python", {{ .Values.inference.command }}]
      tty: true
      stdin: true  
      volumeMounts:
        - mountPath: /data
          name: sapbertdata
      resources:
        {{ $resources | toYaml | nindent 12 }}
  restartPolicy: OnFailure
  volumes:
    - name: sapbertdata
      persistentVolumeClaim:
        claimName: sapbertdata

