{{ $dataPath := include "modelPath" . | trim  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nemo-web-server.fullname" . }}-scripts-configmap
  labels:
    {{- include "nemo-web-server.labels" . | nindent 4 }}
data:
  download.sh: |-
    export DATA_DIR=${DATA_DIR:-'{{ $dataPath }}'}
    echo ${DATA_DIR}
    test -f ${DATA_DIR}${FILE_NAME} || wget -P ${DATA_DIR} ${URL}
