apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}-service
    app.kubernetes.io/instance: {{ .Values.app.name }}-service
    service-type: webserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}-deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    service-type: webserver
