# Default values for nemo-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renci/nemo-sapbert
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "22.01"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

inference:
  resources:
    limits:
      cpu: 2
      memory: 50Gi
      ephemeral-storage: 10Gi
      nvidia.com/mig-2g.10gb: 1
  command: "/data/code/inference_on_pubmed_gpu.py"     
  storage:
    dataStorageSize: 10Gi
    experimentsStorageSize: 20Gi
    scratchStorageSize: 100Gi
    codeDirStorageSize: 1Gi

jupyter:
  enabled: true
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/enable-cors: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
    - host: sapbert-jupyter.apps.renci.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    tls:
     - secretName: sapbert-jupyter.apps.renci.org-tls
       hosts:
         - sapbert-jupyter.apps.renci.org

  resources:
    limits:
      cpu: 1
      memory: 4Gi

